#!/bin/bash

## Lets get in our keys and make the necessary files
## Because nsenter has issues entering a container that has environment variables that contain spaces, we are going to change the SSL* vars so we can docker-enter without problems

[ "$SSL_KEY" ] && echo -en "$SSL_KEY" > /etc/nginx/ssl/domain.key && export SSL_KEY=Success
[ "$SSL_CERT" ] && echo -en "$SSL_CERT" > /etc/nginx/ssl/domain.crt && export SSL_CERT=Success
[ "$SSL_TRUST_CERT" ] && echo -en "$SSL_TRUST_CERT" > /etc/nginx/ssl/trust.crt && export SSL_TRUST_CERT=Success



## And maybe they want some ramcache?

[ $RAMCACHE_LOC ] && mkdir -p $RAMCACHE_LOC && mount -t tmpfs -o size=$RAMCACHE_SIZE tmpfs $RAMCACHE_LOC

## I think we are ready!!!
nginx
